faktuu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("invoices/", include("invoices.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"), # use to read template directly from html, without logic
]

invoices/urls.py
from django.urls import path

from . import views

app_name = "invoices"
urlpatterns = [
    # All invoices
    path("", views.invoices, name="invoices"),
    # Create invoice
    path("create", views.invoiceCreate, name="invoiceCreate"),
    # Show invoice
    path("<int:invoice_id>/", views.invoiceDetail, name="invoiceDetail"),
     # Delete invoice
    path("invoices/<int:invoice_id>/delete", views.invoiceDelete, name="invoiceDelete"),
    # Create PDf from invoice
    path("<int:invoice_id>/pdf/", views.generateInvoicePdf, name="generateInvoicePdf"),
    # Filter invoices
    path("filter-invoices/", views.filterInvoices, name="filterInvoices"),

    # Show all clients
    path("clients", views.clients, name="clients"),
    # Create client
    path("clients/create", views.clientForm, name="clientForm"),
    # Show client
    path("clients/<int:client_id>/", views.clientDetail, name="clientDetail"),
    # Delete client
    path("clients/<int:client_id>/delete", views.clientDelete, name="clientDelete"),
    # Filter clients
    path("clients/filter-clients/", views.filterClients, name="filterClients"),
     # Get one invoice
    path("clients/get-client/<int:client_id>/", views.getClient, name="getClient"),

    # /invoices/products
    path("products", views.products, name="products"),
    # /invoices/products/create
    path("products/create", views.productForm, name="productForm"),
    # /invoices/products/5
    path("products/<int:product_id>/", views.productDetail, name="productDetail"),
    # /invoices/products/5/delete
    path("products/<int:product_id>/delete", views.productDelete, name="productDelete"),
    # /invoices/products/filter-products
    path("products/filter-products/", views.filterProducts, name="filterProducts"),
    # /invoices/products/get-products
    path("products/get-products/", views.getProducts, name="getProducts"),
]

invoices/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Product, Client, Invoice, InvoiceProduct

class ProductForm(forms.ModelForm):
    class Meta:
        VALUE_TAX = [
            (23, 23),
            (8, 8),
            (7, 7),
            (5, 5),
            (4, 4),
            (0, 0),
        ]
        model = Product
        fields = ['name', 'price_netto', 'tax', 'price_brutto']
        labels = {
            "name":  "Nazwa *",
            "price_netto": "Cena Netto *",
            "tax": "Podatek VAT *",
            "price_brutto": "Cena Brutto *",
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj nazwę produktu'}),
            'price_netto': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Cena netto'}),
            'tax': forms.Select(attrs={'class': 'form-control'}),
            'price_brutto': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Cena brutto'}),
        }

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'nip_number', 'street', 'city', 'postal_code', 'country', 'phone_number', 'email']
        labels = {
            "name":  "Nazwa *",
            "nip_number": "Numer NIP *",
            "street": "Ulica",
            "city": "Miasto",
            "postal_code": "Kod Pocztowy",
            "country": "Kraj",
            "phone_number": "Numer Telefonu",
            "email": "Adres Email",
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj nazwę klienta'}),
            'nip_number': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj NIP'}),
            'street': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj ulicę'}),
            'city': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj miasto'}),
            'postal_code': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj kod pocztowy'}),
            'country': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj kraj'}),
            'phone_number': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj numer telefonu'}),
            'email': forms.EmailInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj adres e-mail'}),
        }

class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ['client', 'issue_date', 'sale_date', 'payment_method', 'due_date', 'bank_account']
        labels = {
            "client":  "Nazwa klienta",
            "issue_date": "Data wydania",
            "sale_date": "Data sprzedazy",
            "payment_method": "Sposób płatnośści",
            "due_date": "Termin płatności",
            "bank_account": "Numer bankowy"
        }
        widgets = {
            'client': forms.Select(),
            'issue_date': forms.DateInput(attrs={'type': 'date'}),
            'sale_date': forms.DateInput(attrs={'type': 'date'}),
            'payment_method': forms.Select(),
            'due_date': forms.DateInput(attrs={'type': 'date'}),
            'bank_account': forms.TextInput(attrs={'class': 'custom-input', 'placeholder': 'Podaj numer bankowy'}),
        }

    # show only clients assigned to the user
    def __init__(self, *args, assignedTo=None, **kwargs):
        super().__init__(*args, **kwargs)
        if assignedTo:
            self.fields["client"].queryset = Client.objects.filter(assigned_to=assignedTo)

class InvoiceProductForm(forms.ModelForm):
    class Meta:
        model = InvoiceProduct
        fields = ['name', 'price', 'quantity']

InvoiceProductFormSet = inlineformset_factory(
    Invoice, 
    InvoiceProduct,
    form=InvoiceProductForm,
    extra=1, 
    can_delete=False 
)

invoices/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, FileResponse, HttpResponseForbidden, JsonResponse
from .models import Invoice, InvoiceCounter, Client, Product, InvoiceProduct
from .forms import ProductForm, ClientForm, InvoiceForm, InvoiceProductFormSet
from django.urls import reverse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.template.loader import get_template
from django.db.models import Q
import io
from xhtml2pdf import pisa

# Invoices
@login_required()
def invoices(request):
    all_invoices = Invoice.objects.filter(assigned_to=request.user)
    print(request.user)
    context = {
        "all_invoices": all_invoices,
    }
    return render(request, "invoices/invoices.html", context)
    
# Create invoice
@login_required()
def invoiceCreate(request):
    createdProducts = Product.objects.filter(assigned_to=request.user)
    print(createdProducts)
    if request.method == "POST":
        form = InvoiceForm(request.POST, assignedTo=request.user)
        if form.is_valid():
            invoice = form.save(commit=False)
            invoice.total_netto = request.POST.get('totalNetto')
            invoice.total_vat = request.POST.get('totalVat')
            invoice.total_brutto = request.POST.get('totalBrutto')
            invoice.assigned_to = request.user
            print(request.user)
            invoice.save(user=request.user)
            productsName = request.POST.getlist("productName[]")
            productsPrice = request.POST.getlist("productPrice[]")
            productsTax = request.POST.getlist("productTax[]")
            productsQuantity = request.POST.getlist("productQuantity[]")
            for index in range(len(productsName)):
                InvoiceProduct.objects.create(
                    invoice = invoice,
                    name = productsName[index],
                    price = productsPrice[index],
                    tax = productsTax[index],
                    quantity = int(productsQuantity[index])
                )
        return HttpResponseRedirect(reverse("invoices:invoices"))
    else:
        form = InvoiceForm(assignedTo=request.user)
    return render(request, "invoices/invoiceForm.html", {"form": form, "createdProducts": createdProducts})


# Detail
@login_required()
def invoiceDetail(request, invoice_id):
    # get invoice data
    invoice = get_object_or_404(Invoice, pk=invoice_id)
    createdProducts = Product.objects.filter(assigned_to=request.user)
    print(createdProducts)
    if invoice.assigned_to != request.user:
        return HttpResponseRedirect(reverse("invoices:invoices"))
    else:
        products = invoice.products.all()
        # update invoice data
        if request.method == "POST":
            form = InvoiceForm(request.POST, instance=invoice, assignedTo=request.user)
            print(request.POST)
            if form.is_valid():
                invoice = form.save(commit=False)
                invoice.total_netto = request.POST.get('totalNetto')
                invoice.total_vat = request.POST.get('totalVat')
                invoice.total_brutto = request.POST.get('totalBrutto')
                invoice = form.save()
                id_existing_products = []
                id_updated_product = []
                # add invoiceProduct id to list
                for product in products:
                    id_existing_products.append(product.id)
                # get data from form
                productsId = request.POST.getlist("productId[]")
                productsName = request.POST.getlist("productName[]")
                productsPrice = request.POST.getlist("productPrice[]")
                productsTax = request.POST.getlist("productTax[]")
                productsQuantity = request.POST.getlist("productQuantity[]")
                for index in range(len(productsName)):
                    # update existing invoiceProduct
                    print(productsId)
                    if productsId[index] in id_existing_products:
                        product = products.filter(id=productsId).first()
                        product.name = productsId[index]
                        product.price = productsPrice[index]
                        product.quantity = productsQuantity[index]
                        product.save()
                        id_updated_product.append(productsId[index])
                    # create new invoiceProduct
                    else:
                        InvoiceProduct.objects.create(
                            invoice = invoice,
                            name = productsName[index],
                            price = productsPrice[index],
                            tax = productsTax[index],
                            quantity = int(productsQuantity[index])
                        )
                # delete invoiceProduct which was deleted in form
                for id_exist in id_existing_products:
                    if id_exist not in id_updated_product:
                        products.filter(id=id_exist).first().delete()
                return HttpResponseRedirect(reverse("invoices:invoices"))
        # show invoice data
        else:
            form = InvoiceForm(instance=invoice, assignedTo=request.user)
        return render(request, "invoices/invoiceForm.html", {"form": form, "products":products, "invoice":invoice, "createdProducts": createdProducts})

# Delete Invoice
@login_required()
def invoiceDelete(request, invoice_id):
    invoice = get_object_or_404(Invoice, pk=invoice_id)
    if invoice.assigned_to != request.user:
        return HttpResponseRedirect(reverse("invoices:invoices"))
    else:
        if request.method == "POST":
            invoice.delete()
            return HttpResponseRedirect(reverse("invoices:invoices"))
        return render(request, "invoices/invoiceDetail.html", {"invoice": invoice})

# Generate PDF
@login_required()
def generateInvoicePdf(request, invoice_id):
    invoice = get_object_or_404(Invoice, id=invoice_id)
    if invoice.assigned_to != request.user:
        return HttpResponseRedirect(reverse("invoices:invoices"))
    else:
        products = invoice.products.all()

        # get html template
        template_path = "pdf/invoicePdf.html"
        context = {"invoice": invoice, "products": products, "user": request.user}
        template = get_template(template_path)
        html = template.render(context)

        # issue with polish signs, the helpful font is Open Sans
        # convert html to pdf
        response = HttpResponse(content_type="application/pdf")
        response["Content-Disposition"] = f'attachment; filename="faktura_{invoice.invoice_number}.pdf"'
        pisa_status = pisa.CreatePDF(io.BytesIO(html.encode("UTF-8")), dest=response)

        if pisa_status.err:
            return HttpResponse("Błąd przy generowaniu PDF", status=500)

        return response
    
# Filter Invoices
@login_required()
def filterInvoices(request):
    query = request.GET.get("query", "").strip()
    if not query: 
        invoices = Invoice.objects.filter(assigned_to=request.user)
    else: 
        invoices = Invoice.objects.filter(
            Q(assigned_to=request.user) & (
                Q(invoice_number__icontains=query) |
                Q(client__name__icontains=query)
            )
        )

    print(invoices)
    
    invoice_data = list(invoices.values("id", "invoice_number", "client__name"))
    print(invoice_data)
    
    return JsonResponse({"invoices": invoice_data})

# clients
@login_required()
def clients(request):
    all_clients = Client.objects.filter(assigned_to=request.user)
    context = {
        "all_clients": all_clients,
    }
    return render(request, "invoices/clients.html", context)

# Create New Client
@login_required()
def clientForm(request):
    if request.method == "POST":
        form = ClientForm(request.POST)
        print(form)
        if form.is_valid():
            client = form.save(commit=False)
            client.assigned_to = request.user
            client = form.save()
            return HttpResponseRedirect(reverse("invoices:clients"))
    else:
        form = ClientForm()

    return render(request, "invoices/clientform.html", {"form": form})

# Client Detail
@login_required()
def clientDetail(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    if client.assigned_to != request.user:
        return HttpResponseRedirect(reverse("invoices:clients"))
    else:
        if request.method == "POST":
            form = ClientForm(request.POST, instance=client)  
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse("invoices:clients"))
        else:
            form = ClientForm(instance=client)
        return render(request, "invoices/clientDetail.html", {"form":form, "client": client})

# Delete Client
@login_required()
def clientDelete(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    if client.assigned_to != request.user:
        return HttpResponseRedirect(reverse("invoices:clients"))
    else:
        if request.method == "POST":
            client.delete()
            return HttpResponseRedirect(reverse("invoices:clients"))
        return render(request, "invoices/clientDetail.html", {"client": client})
    
# Filter Clients
@login_required()
def filterClients(request):
    query = request.GET.get("query", "").strip()
    print(query)
    if not query: 
        clients = Client.objects.filter(assigned_to=request.user)
    else: 
        clients = Client.objects.filter(
            Q(assigned_to=request.user) & (
                Q(name__icontains=query) |
                Q(nip_number__icontains=query)
            )
        )
    
    client_data = list(clients.values("id", "name", "nip_number"))
    
    return JsonResponse({"clients": client_data})

# Get one Client

invoices/templates/invoices/clients.html
{% extends 'baseInvoice.html' %}

{% block title %}Klienci{% endblock %}

{% block titlePage %}Klienci{% endblock %}

{% block button %}<a href="{% url 'invoices:clientForm' %}" class="btn">Dodaj Klienta</a>{% endblock %}

{% block content %}
    <input type="text" id="searchInput" name="searchInput" placeholder="Wyszukaj klientów...">
    <div class="grid" id="productGrid">
        {% for client in all_clients %}
        <a href="{% url 'invoices:clientDetail' client.id %}" class="clickable-card">
            <h2>{{ client.name }}</h2>
            <p>NIP: {{ client.nip_number }}</p>
        </a>
        {% endfor %}
    </div>
    {% if not all_clients %}
        <p>Brak klientów.</p>
    {% endif %}
{% endblock %}

{% block script %}
<script>
    let timeout;
    const searchInput = document.getElementById("searchInput");
    searchInput.addEventListener("input", function (event) {
        clearTimeout(timeout);

        timeout = setTimeout(() => {
            let query = event.target.value;
            fetch(`/invoices/clients/filter-clients/?query=${query}`, {
                method: "GET",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": getCSRFToken()
                }
            })
            
            .then(response => response.json())
            .then(data => {
                let productGrid = document.getElementById("productGrid");
                productGrid.innerHTML = "";

                if (data.clients.length > 0) {
                    data.clients.forEach(client => {
                        let productCard = document.createElement("a");
                        productCard.href = `/invoices/clients/${client.id}`;
                        productCard.classList.add("clickable-card");

                        let h2 = document.createElement("h2");
                        h2.textContent = client.name;

                        let p = document.createElement("p");
                        p.textContent = `${client.nip_number}`;

                        productCard.appendChild(h2);
                        productCard.appendChild(p);
                        productGrid.appendChild(productCard);
                    });
                } else {
                    productGrid.innerHTML = "<p>Brak wyników.</p>";
                }
            })
            .catch(error => console.error("Błąd:", error));

        }, 500);
    })

    function getCSRFToken() {
        return document.querySelector('[name=csrfmiddlewaretoken]').value;
    }
</script>
{% endblock %}

invoices/templates/invoices/invoiceForm.html
{% extends 'baseInvoice.html' %}

{% block title %}
{% if invoice.invoice_number %}
{{invoice.invoice_number}}
{% else %}
Dodaj Fakturę Sprzedazy
{% endif %}
{% endblock %}

{% block titlePage %}
{% if invoice.invoice_number %}
{{invoice.invoice_number}}
{% else %}
Dodaj Fakturę Sprzedazy
{% endif %}
{% endblock %}

{% block button %}
{% if invoice.id %}
<form method="post" action="{% url 'invoices:generateInvoicePdf' invoice.id %}">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">Wygeneruj PDF</button>
</form>
<form method="post" action="{% url 'invoices:invoiceDelete' invoice.id %}">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">Usuń fakturę</button>
</form>
{% else %}

{% endif %}

{% endblock %}

{% block content %}
<form method="post" class="form-container">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.client.id_for_label }}">{{ form.client.label }}</label>
        {{ form.client }}
    </div>
    <div class="form-group">
        <label>Numer NIP:</label>
        <p id="client-nip"></p>
    </div>
    <div class="form-group">
        <label>Adres:</label>
        <p id="client-street"></p>
        <p id="client-city"></p>
    </div>

    <div class="form-group">
        <label for="{{ form.issue_date.id_for_label }}">{{ form.issue_date.label }}</label>
        {{ form.issue_date }}
    </div>

    <div class="form-group">
        <label for="{{ form.sale_date.id_for_label }}">{{ form.sale_date.label }}</label>
        {{ form.sale_date }}
    </div>

    <div class="form-group">
        <label for="{{ form.payment_method.id_for_label }}">{{ form.payment_method.label }}</label>
        {{ form.payment_method }}
    </div>
    <div class="form-group">
        <label for="{{ form.due_date.id_for_label }}">{{ form.due_date.label }}</label>
        {{ form.due_date }}
    </div>
    <div class="form-group">
        <label for="{{ form.bank_account.id_for_label }}">{{ form.bank_account.label }}</label>
        {{ form.bank_account }}
    </div>
    <input id="totalNettoInput" type="hidden" name="totalNetto" value="">
    <input id="totalVatInput" type="hidden" name="totalVat" value="">
    <input id="totalBruttoInput" type="hidden" name="totalBrutto" value="">
    <div id="product-container">
        {% for product in products %}
        <div class="product-entry" data-index="{{ forloop.counter0 }}">
            <input type="hidden" name="productId[]" value={{product.id}}>
            <label>Nazwa produktu:</label>
            <input type="text" name="productName[]" placeholder="Nazwa" value={{product.name}}>

            <label>Ilość:</label>
            <input type="number" class="productQuantity" name="productQuantity[]" placeholder="Ilość"
                value={{product.quantity}}>

            <label>VAT:</label>
            <select id="tax" class="productTax" name="productTax[]">
                <option value="23" {% if product.tax == 23 %}selected{% endif %}>23%</option>
                <option value="8" {% if product.tax == 8 %}selected{% endif %}>8%</option>
                <option value="7" {% if product.tax == 7 %}selected{% endif %}>7%</option>
                <option value="5" {% if product.tax == 5 %}selected{% endif %}>5%</option>
                <option value="4" {% if product.tax == 4 %}selected{% endif %}>4%</option>
                <option value="0" {% if product.tax == 0 %}selected{% endif %}>0%</option>
            </select>

            <label>Cena:</label>
            <input type="number" class="productPrice" name="productPrice[]" placeholder="Cena" value={{product.price}}>

            <button id="remove-product-{{ forloop.counter0 }}" type="button" class="btn btn-primary">Usuń
                produkt</button>
            <button id="add-exist-product-{{ forloop.counter0 }}" type="button" class="btn btn-primary">Dodaj</button>
            {% with outer_loop_counter=forloop.counter0 %}
            <ul class="dropdown-products" id="dropdownProducts">
                {% for createdProduct in createdProducts %}
                <li>
                    <button class="delete-btn" data-product-index={{ forloop.counter0 }} data-index={{ outer_loop_counter }}>{{ createdProduct.name }}</button>
                    
                </li>
                {% endfor %}

            </ul>
            {% endwith %}
        </div>
        {% empty %}

        {% endfor %}
    </div>
    <button id="add-product" type="button" class="btn btn-primary">Dodaj produkt</button>
    <button type="submit" class="btn btn-primary">Zapisz fakturę</button>
    <a href="{% url 'invoices:invoices' %}" class="btn btn-secondary">Anuluj</a>
</form>
<div class="bottombar">
    <p>Netto: <span id="totalNetto">0.00</span> PLN</p>
    <p>VAT: <span id="totalVat">0.00</span> PLN</p>
    <p>Suma: <span id="totalBrutto">0.00</span> PLN</p>
</div>

{% endblock %}

{% block script %}
<script>
    //get list user products
    userProducts = {}

    //get client data
    clientData = {}

    document.addEventListener("DOMContentLoaded", function () {
        fetch("/invoices/products/get-products/")
            .then(response => response.json())
            .then(data => {
                userProducts = data.products;
            })
            .catch(error => console.error("Błąd pobierania danych:", error));
    });
    
    let maxIndex = 0;
    // get highest product index
    let elements = document.querySelectorAll("[data-index]");
    elements.forEach(element => {
        let index = parseInt(element.dataset.index);
        if (index > maxIndex) {
            maxIndex = index;
        }
    });

    // get data for choose client
    const clientSelect = document.getElementById("{{ form.client.auto_id }}");

    clientSelect.addEventListener("change", () => {
        const clientId = clientSelect.value;

        fetch(`/invoices/clients/get-client/${clientId}/`)
            .then(response => response.json())
            .then(data => {
                clientData = data.client;
                console.log(clientData)
                document.getElementById('client-nip').innerText = clientData[0].nip_number;
                document.getElementById('client-street').innerText = clientData[0].street;
                document.getElementById('client-city').innerText = `${clientData[0].postal_code} ${clientData[0].city}`;
            })
            .catch(error => console.error("Błąd pobierania danych:", error));
    });

    // calculate sum of price of all products
    function calculateTotal() {
        let totalNetto = 0;
        let totalVat = 0;
        let totalBrutto = 0;
        const prices = document.querySelectorAll(".productPrice");
        const vats = document.querySelectorAll(".productTax");
        const quantities = document.querySelectorAll(".productQuantity");

        prices.forEach((priceInput, index) => {
            const price = parseFloat(priceInput.value);
            const tax = parseInt(vats[index].value);
            const quantity = parseInt(quantities[index].value);

            if (!isNaN(price) && !isNaN(quantity)) {
                const productTotal = price * quantity;
                const vatTotal = price * quantity * tax / 100;
                totalNetto += productTotal;
                totalVat += vatTotal;
                totalBrutto += productTotal + vatTotal;
            }
        })


        document.getElementById("totalNetto").textContent = totalNetto.toFixed(2);
        document.getElementById("totalVat").textContent = totalVat.toFixed(2);
        document.getElementById("totalBrutto").textContent = totalBrutto.toFixed(2);

        document.getElementById("totalNettoInput").value = totalNetto.toFixed(2);
        document.getElementById("totalVatInput").value = totalVat.toFixed(2);
        document.getElementById("totalBruttoInput").value = totalBrutto.toFixed(2);
    }

    calculateTotal();

    // add div with new product
    document.getElementById("add-product").addEventListener("click", function (event) {
        event.preventDefault();
        maxIndex = maxIndex + 1;
        console.log(maxIndex)
        let container = document.getElementById("product-container");

        let newProduct = document.createElement("div");
        newProduct.classList.add("product-item");

        let dropdownHTML = '';
        userProducts.forEach((product, index) => {
            console.log(maxIndex)
            dropdownHTML += `<li>
                <button class="delete-btn" data-product-index=${index} data-index=${maxIndex}>${product.name}</button>
            </li>`;
        });

        newProduct.innerHTML = `
            <div class="product-entry" data-index="${maxIndex}">
                <input type="hidden" name="productId[]" value="">
                <label>Nazwa produktu:</label>
                <input type="text" name="productName[]"placeholder="Nazwa">

                <label>Ilość:</label>
                <input type="number" class="productQuantity" name="productQuantity[]" placeholder="Ilość" value=0>

                 <label>VAT:</label>
                    <select id="tax" class="productTax" name="productTax[]" placeholder="VAT" value=23>
                        <option value="23">23%</option>
                        <option value="8">8%</option>
                        <option value="7">7%</option>
                        <option value="5">5%</option>
                        <option value="4">4%</option>
                        <option value="0">0%</option>
                    </select>

                <label>Cena:</label>
                <input type="number" class="productPrice" name="productPrice[]" placeholder="Cena" value=0>

                <button id="remove-product-${maxIndex}" type="button" class="btn btn-primary">Usuń produkt</button>
                <button id="add-exist-product-${maxIndex}" type="button" class="btn btn-primary">Dodaj</button>
                <ul class="dropdown-products" id="dropdownProducts">
                    ${dropdownHTML}
                </ul>
            </div>
            `;

        container.appendChild(newProduct);
    })

    // delete div with product
    document.getElementById("product-container").addEventListener("click", function (event) {
        if (event.target) {
            let productId = event.target.id.replace("remove-product-", "");
            let productEntry = document.querySelector(`.product-entry[data-index='${productId}']`);

            if (productEntry) {
                productEntry.remove();
            }
        }
    });

    // fill product inputs
    document.getElementById("product-container").addEventListener("click", function (event) {
        event.preventDefault();
        if (event.target && event.target.classList.contains('delete-btn')) {
            let productIndex = event.target.dataset.productIndex;
            let maxIndex = event.target.dataset.index;
            console.log(productIndex, maxIndex)

            let productEntry = document.querySelector(`.product-entry[data-index='${maxIndex}']`);
            if (productEntry) {
                let nameInput = productEntry.querySelector("input[name='productName[]']");
                let taxSelect = productEntry.querySelector("select[name='productTax[]']");
                // let quantityInput = productEntry.querySelector("input[name='productQuantity[]']");
                let priceInput = productEntry.querySelector("input[name='productPrice[]']");
                
                nameInput.value = userProducts[productIndex].name;
                taxSelect.value = userProducts[productIndex].tax;
                priceInput.value = userProducts[productIndex].price_netto;
        }
    }
    })

    // show/hide dropdown menu
    document.getElementById("product-container").addEventListener("click", function (event) {
        event.preventDefault();
        if (event.target) {
            let productId = event.target.id.replace("add-exist-product-", "");
            let productEntry = document.querySelector(`.product-entry[data-index='${productId}']`);

            if (productEntry) {
                let dropdownMenu = productEntry.querySelector("ul[id='dropdownProducts']");
                if (dropdownMenu.style.display === "block") {
                    dropdownMenu.style.display = "none";
                    } else {
                        dropdownMenu.style.display = "block";
                    }
            }
        }
    })

    // Event delegation
    document.getElementById("product-container").addEventListener("input", function (event) {
        if (event.target.classList.contains("productPrice") || event.target.classList.contains(
                "productQuantity") || event.target.classList.contains("productTax")) {
            calculateTotal();
        }
    });

    document.querySelectorAll(".productPrice, .productQuantity, .productTax").forEach(item => {
        item.addEventListener("input", calculateTotal);
    })
</script>
{% endblock %}