faktuu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("invoices/", include("invoices.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"), # use to read template directly from html, without logic
]

invoices/urls.py
from django.urls import path

from . import views

app_name = "invoices"
urlpatterns = [
    # All invoices
    path("", views.invoices, name="invoices"),
    # Create invoice
    path("create", views.invoiceCreate, name="invoiceCreate"),
    # Show invoice
    path("<int:invoice_id>/", views.invoiceDetail, name="invoiceDetail"),
     # Delete invoice
    path("invoices/<int:invoice_id>/delete", views.invoiceDelete, name="invoiceDelete"),
    # Create PDf from invoice
    path("<int:invoice_id>/pdf/", views.generateInvoicePdf, name="generateInvoicePdf"),
    # Filter invoices
    path("filter-invoices/", views.filterInvoices, name="filterInvoices"),

    # Show all clients
    path("clients", views.clients, name="clients"),
    # Create client
    path("clients/create", views.clientForm, name="clientForm"),
    # Show client
    path("clients/<int:client_id>/", views.clientDetail, name="clientDetail"),
    # Delete client
    path("clients/<int:client_id>/delete", views.clientDelete, name="clientDelete"),
    # Filter clients
    path("clients/filter-clients/", views.filterClients, name="filterClients"),
     # Get one invoice
    path("clients/get-client/<int:client_id>/", views.getClient, name="getClient"),

    # /invoices/products
    path("products", views.products, name="products"),
    # /invoices/products/create
    path("products/create", views.productForm, name="productForm"),
    # /invoices/products/5
    path("products/<int:product_id>/", views.productDetail, name="productDetail"),
    # /invoices/products/5/delete
    path("products/<int:product_id>/delete", views.productDelete, name="productDelete"),
    # /invoices/products/filter-products
    path("products/filter-products/", views.filterProducts, name="filterProducts"),
    # /invoices/products/get-products
    path("products/get-products/", views.getProducts, name="getProducts"),
]

faktuu/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}Faktuu{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'home/styles.css' %}">
</head>

<body>
  <main>
    <nav class="navbar">
      <a href="{% url 'home' %}" class="app-name">Faktuu</a>
      <ul class="nav-links">
      {% block navbar %}{% endblock %}
      </ul>
  </nav>
  {% block content %}
  {% endblock %}
  </main>
</body>

</html>

faktuu/templates/home.html
{% extends "base.html" %}

{% block title %}Faktuu{% endblock %}

{% block navbar %}
    {% if user.is_authenticated %}
    <a href="{% url 'invoices:invoices' %}" class="button">Profil</a>
    <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="button">Wyloguj</button>
    </form>
    {% else %}
    <a href="{% url 'login' %}" class="button">Zaloguj</a>
    <a href="{% url 'signup' %}" class="button">Zarejestruj</a>
    {% endif %}
{% endblock %}

{% block content %}

    <h1 class="title">Faktuu</h1>

    <p class="description">
        Twórz, zarządzaj i generuj faktury w prosty sposób! Szybkie wystawianie faktur i pełna kontrola nad Twoimi dokumentami.
    </p>

    <div class="advantages">
        <div class="box">
            <h3>Automatyzacja</h3>
            <p>Nasza aplikacja sama numeruje faktury i ułatwia zarządzanie.</p>
        </div>
        <div class="box">
            <h3>Szybkość</h3>
            <p>Tworzenie faktur zajmuje tylko kilka sekund!</p>
        </div>
    </div>
{% endblock %}